kind: pipeline
name: default

steps:
- name: setup
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: remiliaforever/bilibili-live-notifier
    tags: latest

- name: build
  image: remiliaforever/bilibili-live-notifier:latest
  pull: always
  commands:
  - export CARGO_HOME=./.cargo
  - cargo build

- name: test
  image: remiliaforever/bilibili-live-notifier:latest
  commands:
  - cargo tarpaulin --out Xml -v

- name: codecov
  image: robertstettner/drone-codecov
  pull: always
  settings:
    token:
      from_secret: codecov_token
    files:
    - cobertura.xml

- name: notify
  image: appleboy/drone-telegram
  pull: always
  when:
      status:
      - success
      - failure
  settings:
    format: markdown
    to: -155562062
    message: |
        {{#success build.status}}
            *Success* [{{repo.owner}}/{{repo.name}} #{{build.number}}]({{build.link}})
        {{else}}
            *Failed* {{build.link}}
        {{/success}}
        *Branch*: {{commit.Branch}}
        *Author*: {{commit.Author}}
        *Message*: {{commit.Message}}
        *Elapsed*: {{buildtime build.started}}
    token:
      from_secret: telegram_token
