[package]
name = "bilibili-live-notifier"
version = "0.1.0"
authors = ["RemiliaForever <remilia@koumakan.cc>"]

[dependencies]
byteorder = "1.2.6"
chrono = "0.4.6"
notify-rust = "3.4.2"
serde_json = "1.0.26"
